Badger-Finance/badger-api

- src/interface/Claw.ts
- src/service/claw/ClawService.ts
Adds some additional fields to the synthetic data schema.
> feat: add additional emp fields

- src/service/claw/ClawService.ts
> fix: do math

- tsconfig.json
This is breaking the API from starting - will take another look around and come back to it if needed.
> fix(badger-api): Remove `incremental` from `tsconfig.json`

- .env.development
- .eslintrc.js
- codegen.yml
- package.json
- serverless.yml
- src/graphql/generated/badger-dao.ts
- src/graphql/generated/badger.ts
- src/graphql/generated/masterchef.ts
- src/graphql/generated/sushiswap.ts
- src/graphql/generated/uniswap.ts
- yarn.lock
* Add `dotenv` and create `.env.development` file to store some environment variables. 
* Add `graphql-codegen` and pull in schemas from Badger, MasterChef, SushiSwap, and UniSwap subgraphs
> feat(badger-api): Add graphql-codegen and generate protocol schemas

- src/graphql/generated/badger-dao.ts
- src/graphql/generated/badger.ts
- src/graphql/generated/masterchef.ts
- src/graphql/generated/sushiswap.ts
- src/graphql/generated/uniswap.ts
- src/indexer/curve/handler.ts
- tsconfig.json
These are causing some compilation issues, so cleaning up unused imports.
> refactor(badger-api): Clean up generated code

- src/interface/Claw.ts
- src/service/claw/ClawService.ts
Raw ethers output is [] w/ no fields.
> chore: format claw data

- .env.development
- codegen.yml
- serverless.yml
- src/graphql/generated/badger-dao.ts
- src/graphql/generated/sushiswap.ts
- src/graphql/queries/harvests.query.graphql
* Update Badger DAO subgraph URL
* Re-generate schemas
* Add query to fetch harvests via Badger DAO
> feat(badger-api): Generate query wrapper for fetching harvests

- src/interface/Claw.ts
- src/service/claw/ClawService.ts
Adds a single field (token currency address) to claws endpoint.
> feat: add token currency field to claws endpoint

- codegen.yml
- src/config/util.ts
- src/graphql/fragments/sett.fragment.graphql
- src/graphql/generated/badger.ts
- src/graphql/queries/setts.query.graphql
- src/indexer/curve/handler.ts
- src/indexer/indexer.ts
- src/indexer/sushiswap/handler.ts
- src/indexer/uniswap/handler.ts
Pull in Sett and query types from subgraph definition.
> feat(badger-api): Generate types for Sett query from codegen

- src/protocols/strategies/mstable.strategy.ts
- src/rewards/rewards.utils.ts
Badger is no longer supporting mStable and this custom code does not fit into the new API paradigm.
> chore: remove mstable custom code

- src/chains/config/eth.config.ts
- src/vaults/__snapshots__/vaults.controller.spec.ts.snap
- src/vaults/interfaces/vault-definition.interface.ts
- src/vaults/vaults.service.ts
Reverts Badger-Finance/badger-api#999
> Revert "chore: deprecate vaults"

- src/accounts/accounts.utils.spec.ts
- src/accounts/accounts.utils.ts
- src/indexers/vault-snapshots-indexer.spec.ts
- src/protocols/strategies/convex.strategy.ts
- src/test/tests.utils.ts
- src/tokens/__snapshots__/tokens.utils.spec.ts.snap
- src/tokens/tokens.utils.spec.ts
- src/tokens/tokens.utils.ts
- src/vaults/vaults.controller.spec.ts
- src/vaults/vaults.service.ts
- resolve issue causing single token deposits to return no tokens
> chore: resolve single token balances

- src/gas/gas.service.spec.ts
https://github.com/Badger-Finance/badger-api/issues/737
> test(badger-api): Add `gas.service.spec.ts`

- src/Server.ts
- src/config/constants.ts
- src/config/util.ts
> Verify env variables

- src/CitadelControllerRegistry.ts
- src/ControllerRegistry.ts
- src/Server.ts
- src/citadel/citadel-indexer.ts
- src/citadel/citadel.controller.ts
- src/citadel/citadel.service.ts
- src/citadel/interfaces/citadel-treasury-summary-model.interface.ts
- src/citadel/interfaces/citadel-treasury-summary.interface.ts
Add an initial endpoint for Citadel DAO treasury inspection.
> chore: add initial citadel treasury endpoint

- package.json
- src/citadel/citadel.controller.spec.ts
- src/citadel/citadel.service.spec.ts
- src/rewards/__snapshots__/reward.controller.spec.ts.snap
- src/treasury/examples/treasury-summary.mock.ts
- yarn.lock
Adds tests for new citadel controller + service.
> chore: initial citadel tests

- package.json
- src/citadel/citadel.controller.spec.ts
- src/citadel/citadel.service.spec.ts
- src/treasury/treasury-indexer.ts
- yarn.lock
Fix issue causing data blobs to not be saved with corresponding time frame to correctly insert / delete items.
> chore: update citadel service test snapshots

- src/citadel/citadel.controller.ts
- src/citadel/citadel.service.ts
- src/citadel/citadel.utils.ts
- src/citadel/interfaces/citadel-account.interface.ts
Add an API based skeleton implementation for information required by the portfolio page.
> feat: initial citadel accounts endpoint

- src/chains/config/eth.config.ts
- src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Reverts Badger-Finance/badger-api#1214
> Revert "chore: deprecate digg"

- .github/workflows/deploy.yml
https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931012696
> fix: allow token perms

- src/accounts/__snapshots__/accounts.utils.spec.ts.snap
- src/accounts/accounts.utils.ts
- src/aws/models/cached-account.model.ts
- src/indexers/boosts-indexer.ts
- src/indexers/indexer.utils.spec.ts
- src/indexers/leaderboard-indexer.ts
- src/test/tests.utils.ts
Initial removal of redundant, unused code paths.
> chore: initial boost metrics related removals

- src/citadel/citadel.controller.spec.ts
> fix: update test mock

- .github/workflows/deploy.yml
- package.json
- src/accounts/accounts.utils.spec.ts
- src/accounts/accounts.utils.ts
- src/aws/models/cached-boost.model.ts
- src/indexers/accounts-indexer.ts
- src/indexers/leaderboard-indexer.spec.ts
- src/indexers/leaderboard-indexer.ts
- src/indexers/vault-snapshots-indexer.ts
- src/leaderboards/__snapshots__/leaderboards.utils.spec.ts.snap
- src/leaderboards/leaderboards.utils.spec.ts
- src/leaderboards/leaderboards.utils.ts
- src/test/tests.utils.ts
- src/vaults/vaults.utils.spec.ts
- yarn.lock
Cleaned out leader board entries between calls, properly await deletes and entries.
> fix: leaderboard improper boost updating

- .github/workflows/build.yml
Remove step to generate contracts, they are already build and included - and it is causing issues on build.
> chore: remove codegen

- src/chains/config/eth.config.ts
- src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
- Remove guarded tag from graviAura
- Update snapshots
> Unguard graviaura

- package.json
- seed/prices.json
- seed/vault-snapshots.json
- src/vaults/vaults.utils.ts
- yarn.lock
- forces bvecvx to pick from its round regardless of timing
- forces bvecvx to pick from distributions for weighting
> fix: handle bvecvx rounds

- src/indexers/vault-harvests-indexer.ts
- Fixes issue with projected yields if harvests are failing
> chore: ensure yield projection retained

- src/charts/charts.controller.spec.ts
- src/config/config.utils.spec.ts
- src/indexers/vaults-indexer.spec.ts
- src/prices/prices.utils.spec.ts
- src/rewards/rewards.utils.spec.ts
> chore: clean unnecessary console output for test run

- src/tokens/config/eth-tokens.config.ts
> chore: add missing bpt

- src/indexers/vaults-indexer.ts
Suspend indexing till the time migration from VaultsHistoricData complite
> chore: suspend vault indexing for chartDataBlob

- src/rewards/rewards.utils.spec.ts
- src/vaults/vaults.utils.ts
Ensures that emitted values and compounding etc all have the same name
> chore: apr name alignment

- src/indexers/vault-harvests-indexer.ts
- utilizes performance fee to estimate tokens taken by the DAO in harvests
> feat: estimated yield fee scaling

- src/protocols/strategies/balancer.strategy.ts
- corrects balancer swap fee apr based on discord feedback
> fix: update from balancer feedback

- src/vaults/__snapshots__/yields.utils.spec.ts.snap
- src/vaults/yields.utils.spec.ts
- adds final coverages to yield tests
> test: add projected yield coverage

- package.json
- src/dev/dev.utils.ts
- src/indexers/vault-definition-indexer.ts
- src/vaults/vaults.utils.ts
- yarn.lock
- update registry usage for v2
> feat: upd badger sdk, use only registryV2

- serverless.yml
- src/config/constants.ts
> chore: remove old chart infra + data

- src/vaults/yields.utils.spec.ts
- src/vaults/yields.utils.ts
- enforce value boundaries on proper parameters
> fix: calculate yield check

- src/vaults/vaults.utils.ts
- temporary fix while tests + refactoring takes place
> fix: update target block picking

- serverless.yml
- src/protocols/strategies/balancer.strategy.ts
- src/vaults/influence.utils.ts
- src/vaults/vaults.utils.ts
- src/vaults/yields.config.ts
https://github.com/Badger-Finance/bug-reports/issues/10
> chore: update graviaura yield weight

- src/accounts/accounts.v2.controller.ts
- src/accounts/accounts.v3.controller.ts
- src/chains/chains.utils.ts
- src/chains/strategies/base.strategy.ts
- src/charts/charts.controller.ts
- src/gas/gas.controller.ts
- src/leaderboards/leaderboards.controller.ts
- src/prices/prices.controller.spec.ts
- src/prices/prices.controller.ts
- src/proofs/proofs.v2.controller.ts
- src/proofs/proofs.v3.controller.ts
- src/protocols/protocols.controller.ts
- src/protocols/strategies/balancer.strategy.ts
- src/rewards/__snapshots__/reward.v2.controller.spec.ts.snap
- src/rewards/reward.v2.controller.spec.ts
- src/rewards/reward.v2.controller.ts
- src/rewards/rewards.v3.controller.ts
- src/test/mocks.utils.ts
- src/tokens/tokens.controller.ts
- src/vaults/vaults.utils.ts
- src/vaults/vaults.v2.controller.spec.ts
- src/vaults/vaults.v2.controller.ts
- src/vaults/vaults.v3.controller.spec.ts
- src/vaults/vaults.v3.controller.ts
- src/vaults/yields.utils.ts
- force token distributions aprs to be calculated against the snapshot price
> chore: utilize token emitted values at snapshot time

- jest.config.ts
- src/indexers/yield-estimates-indexer.ts
- src/test/constants.ts
- src/tokens/tokens.utils.spec.ts
- src/tokens/tokens.utils.ts
- src/vaults/vaults.config.ts
- src/vaults/vaults.utils.spec.ts
- src/vaults/vaults.utils.ts
- src/vaults/vaults.v2.controller.spec.ts
- src/vaults/yields.utils.spec.ts
- src/vaults/yields.utils.ts
- move calc balance to tokens utils
- add test coverage for query methods
> chore: additions for vaults coverages

- src/indexers/vault-balances-indexer.spec.ts
- src/metrics/__snapshots__/metrics.utils.spec.ts.snap
- src/metrics/metrics.utils.spec.ts
- src/vaults/interfaces/harvest-report.interface.ts
- src/vaults/interfaces/vault-yield-summary.interface.ts
- src/vaults/vaults.config.ts
- src/vaults/yields.utils.ts
- adds documentation for a large portion of yield utility functions
- chunks yield estimations into more readable, understandable helpers
> chore: add documentation to methods + refactor evaluation methods

- src/indexers/yield-estimates-indexer.ts
- src/vaults/vaults.config.ts
- fix issue causing massive yields due to using seconds
> chore: update yield period

- src/vaults/yields.utils.ts
Fixes an issue where inputs to the flywheel function were being inappropriately picked.
> fix: update flywheel inputs

- src/vaults/yields.utils.ts
- corrects inputs for flywheel calculation
> fix: flywheel apr inputs

- serverless.yml
> fix: add projections infra

- src/aws/models/cached-yield-projection.model.ts
- src/aws/models/cached-yield-source.interface.ts
- src/chains/chains.utils.ts
- src/indexers/vault-definition-indexer.ts
- src/indexers/yield-estimates-indexer.ts
- src/vaults/yields.utils.ts
- correct dynamodb data mapper embed type causing missing values
> fix: dynamodb mapper embed type

- src/vaults/influence.utils.ts
- applied influence logic to both bvecvx and graviaura
closes #1494
> chore: apply broad filtering rules

- src/aws/models/vault-definition.model.ts
- src/indexers/vault-harvests-indexer.spec.ts
- src/indexers/vault-harvests-indexer.ts
- src/test/constants.ts
- src/vaults/harvests.utils.spec.ts
- src/vaults/harvests.utils.ts
- capture indexed harvest block against definition
> feat: add vault harvest block persistence

- src/indexers/vault-harvests-indexer.ts
- src/vaults/harvests.utils.ts
- addresses continued issues with persistence
> refactor: update persistence logic

- serverless.yml
- src/indexers/vault-harvests-indexer.ts
- src/vaults/harvests.utils.ts
- src/vaults/influence.utils.ts
- tweaks to shorten rounds to allow vaults to make progress
- increase timeouts to allow for vault progress or job to complete
- reduce block query chunk size to improve job time
> refactor: bvecvx vault logic

- src/vaults/harvests.utils.ts
- fixes the hash key used to query against the aggregated chain address param
```
➜  badger-api git:(staging) ✗ curl http://localhost:3000/v2/vaults/harvests/0xBA485b556399123261a5F9c95d413B4f93107407 | json_pp
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  4374  100  4374    0     0   1941      0  0:00:02  0:00:02 --:--:--  1941
[
{
"amount" : 592.21554948594,
"block" : 15449147,
"estimatedApr" : 2.54514971966025,
"eventType" : "Harvest",
"strategyBalance" : 543027.062352445,
"timestamp" : 1661983794000,
"token" : "0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF"
},
{
"amount" : 3500.675995,
"block" : 15440382,
"estimatedApr" : 21.1788882101941,
"eventType" : "Tree Distribution",
"strategyBalance" : …
```
> fix: update vault harvest query

- serverless.yml
- fixes deployment tables blockers
> refactor: temp table rename for deploy

- src/indexers/vault-balances-indexer.ts
- src/protocols/strategies/__snapshots__/uniswap.strategy.spec.ts.snap
- src/protocols/strategies/balancer.strategy.ts
- src/protocols/strategies/convex.strategy.ts
- src/protocols/strategies/uniswap.strategy.ts
- src/vaults/vaults.service.ts
- fixes keys for token balances
- enforces type checking on token balance types
> fix: update vault balances indexer

- jest.config.ts
- src/patches/graviaura-badger.ts
- src/vaults/__snapshots__/yields.utils.spec.ts.snap
- src/vaults/yields.utils.ts
- adds script to insert a badger emission that was not emitted on chain
> fix: add missing badger patch

- src/vaults/influence.utils.ts
- fix missing balance around locker change
> fix: use fallback balance

- serverless.yml
- src/indexers/indexer.utils.ts
- src/indexers/vault-harvests-indexer.ts
- src/vaults/harvests.utils.ts
- src/vaults/yields.utils.ts
- handles discontinued vaults appropriate
- fixes potential issue with influence emission durations
> refactor: properly handle discontinued vaults, adjust duration measure

- src/chains/vaults/chain.vaults.ts
- support query for development vaults on staging
> feat: allow dev queries

- package.json
- yarn.lock
> chore: update sdk

- src/vaults/harvests.utils.ts
> fix: update query inputs

- src/indexers/vault-definition-indexer.ts
- force vault definitions to update each check
> fix: force update vaults def

- package.json
- src/indexers/vault-definition-indexer.ts
- yarn.lock
- update sdk for vault logic fix
> fix: filter vaults + update sdk

- src/test/constants.ts
- src/vaults/influence.utils.spec.ts
- add coverage for influence vault event filtering
> test: initial influence utils test coverage

- src/indexers/yield-estimates-indexer.ts
- src/tokens/tokens.utils.ts
- add vault log to yield estimate err
> chore: improve error log

- src/tokens/tokens.utils.ts
- fixes NaN value for diff calc
> fix: accomodate no balance token difference

- src/indexers/indexer.utils.ts
- src/indexers/yield-estimates-indexer.ts
- src/tokens/tokens.utils.spec.ts
- src/tokens/tokens.utils.ts
- src/vaults/__snapshots__/yields.utils.spec.ts.snap
- src/vaults/yields.utils.ts
- remove at issue period yield estimation
> fix: remove granular yield estimation

- src/prices/__snapshots__/prices.service.spec.ts.snap
- src/prices/prices.service.spec.ts
- src/prices/prices.service.ts
- src/prices/prices.utils.spec.ts
- src/prices/prices.utils.ts
- src/test/mocks.utils/mock.api.chain.ts
- src/tokens/config/arbitrum-tokens.config.ts
- src/tokens/config/bsc-tokens.config.ts
- src/tokens/config/fantom-tokens.config.ts
- src/tokens/config/polygon-tokens.config.ts
- src/tokens/interfaces/token-config.interface.ts
- adds more price services documentation
- add minor tests coverage for prices service
> fix: update tests, remove duplicate convert

- src/chains/chains.utils.spec.ts
> test: add chain utils coverages

- jest.config.ts
- src/indexers/vault-harvests-indexer.spec.ts
- add vault harvests index coverages
> test: add vaults harvests coverages

- src/vaults/influence.utils.spec.ts
- src/vaults/influence.utils.ts
- add influence utils coverage for balance function
> test: influence balance coverages

- src/indexers/vault-balances-indexer.spec.ts
- src/indexers/vault-balances-indexer.ts
- adds vault balances indexer coverage
> test: add vault balances indexers coverages

- src/indexers/leaderboards-indexer.spec.ts
- src/indexers/leaderboards-indexer.ts
- src/test/mocks.utils/mock.helpers.ts
- adds leaderboards coverage tests
> test: add leaderboards coverage

- jest.config.ts
- src/protocols/strategies/__snapshots__/uniswap.strategy.spec.ts.snap
- src/protocols/strategies/uniswap.strategy.spec.ts
- src/protocols/strategies/uniswap.strategy.ts
- add coverage for uniswap pricing functions
> test: uniswap strategy coverage

- src/protocols/strategies/__snapshots__/sushiswap.strategy.spec.ts.snap
- src/protocols/strategies/sushiswap.strategy.spec.ts
- src/protocols/strategies/sushiswap.strategy.ts
- src/vaults/harvests.utils.spec.ts
- add sushiswap subgraph coverage
> test: add sushiswap coverage

- jest.config.ts
- src/indexers/protocol-metric-indexer.ts
- src/metrics/enums/metric-type.ts
- src/metrics/metrics.utils.ts
- src/protocols/strategies/__snapshots__/balancer.strategy.spec.ts.snap
- src/protocols/strategies/balancer.strategy.spec.ts
- src/protocols/strategies/balancer.strategy.ts
- src/rewards/rewards.utils.ts
- add balancer function coverage
> test: add balancer function coverage

- src/rewards/__snapshots__/rewards.utils.spec.ts.snap
- src/rewards/rewards.utils.spec.ts
- src/rewards/rewards.utils.ts
- adds rewards utils function coverage
> test: add rewards utils coverage

- src/accounts/accounts.utils.ts
- src/tokens/tokens.utils.spec.ts
- src/tokens/tokens.utils.ts
- fixes an issue showing user balance as full vault
> fix: properly scale user balance

- src/Server.ts
- drop swagger
- add full request logging
> chore: update logging + cache

- src/indexers/__snapshots__/indexer.utils.spec.ts.snap
- src/indexers/indexer.utils.spec.ts
- src/test/constants.ts
> test: resolve test timeout
